# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='abstract',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
