# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-04 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='type',
        ),
        migrations.AddField(
            model_name='document',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
