# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-12 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='author',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
