# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0002_auto_20160403_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date',
            field=models.CharField(max_length=30),
        ),
    ]
