# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-24 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0002_auto_20161224_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='slug',
            field=models.TextField(),
        ),
    ]
