# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-22 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0002_auto_20161122_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='first_save_flag',
            field=models.BooleanField(default=False),
        ),
    ]
