# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-20 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0003_auto_20161220_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='type',
            field=models.CharField(default='fa', max_length=20),
            preserve_default=False,
        ),
    ]
