# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-29 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0004_auto_20161224_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='original_filename',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
