# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-20 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0004_forum_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='forumcomment',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
