# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0005_auto_20160403_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date',
            field=models.DateField(),
        ),
    ]
