# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0006_auto_20160403_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(max_length=500, upload_to='uploads/documents/'),
        ),
    ]
