# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-20 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0006_auto_20161220_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumcomment',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
