# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-08 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0007_auto_20160408_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='drive_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
