# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-20 22:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('intranet', '0007_auto_20161220_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumcomment',
            name='content_type',
        ),
        migrations.AddField(
            model_name='forumcomment',
            name='cite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='forumcomment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 12, 20, 22, 25, 29, 40000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
