# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0008_auto_20160508_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='drive_thumbnail',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
