# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-20 22:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0008_auto_20161220_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forumcomment',
            old_name='cite',
            new_name='content_type',
        ),
    ]
