# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-13 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0009_document_drive_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='abstract',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
