# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-20 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0009_auto_20161220_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumcomment',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
