# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-20 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0010_auto_20161220_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
