# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-13 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0011_document_words'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='words',
        ),
    ]
