# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-13 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0014_auto_20160513_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='drive_thumbnail',
        ),
        migrations.AddField(
            model_name='document',
            name='thumbnail',
            field=models.FileField(default=1, max_length=500, upload_to='uploads/documents/'),
            preserve_default=False,
        ),
    ]
