# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-13 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0015_auto_20160513_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='thumbnail',
            field=models.FileField(max_length=500, upload_to='static/thumbnails/'),
        ),
    ]
