# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-18 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0017_auto_20160616_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='pages',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
