# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-18 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0018_document_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
