# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-05 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0019_auto_20160618_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='abstract',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
