from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^document/(?P<author>.*)/(?P<title>.*)/$', views.document, name="document"),
    url(r'^edit/document/(?P<id>.*)/$', views.edit_document, name="edit_document"),
    url(r'^$', views.home, name="home"),
    url(r'^documents/$', views.documents, name="documents"),
    url(r'^search/(?P<search>.*)/$', views.documents, name="intranet_search"),
    url(r'^profile/$', views.profile, name="profile"),
    url(r'^profile/update/picture/$', views.update_profile_picture, name='update_picture'),
    url(r'^profile/(?P<user_id>.*)/$', views.profile, name='profile'),
    url(r'^users/', views.users, name='users'),
    url(r'^upload/extract/$', views.extract_content_and_keywords, name='extract_content'),
    url(r'^upload/$', views.upload, name='upload'),
    url(r'^upload/check/$', views.check_title, name='check_title'),
    url(r'^upload/local/$', views.upload_local, name="local_upload"),
    url(r'^upload/drive/$', views.upload_drive, name="drive_upload"),
    url(r'^upload/form/local/$', views.local_form, name='local_form'),
    url(r'^upload/form/drive/$', views.drive_form, name='drive_form'),
    url(r'^viewer/(?P<author>.*)/(?P<title>.*)/$', views.pdf_viewer, name='viewer'),
    url(r'^viewer/(?P<id>.*)/$', views.pdf_viewer, name='viewer'),
    url(r'^helper/(?P<search>.*)/$', views.search_helper, name="helper"),
    url(r'^news/$', views.news, name='news'),
    url(r'^news/create/written$', views.news_create, name='create_news'),
    url(r'^news/edit/(?P<id>.*)/$', views.news_edit, name='edit_news'),
    url(r'^news/create/link$', views.news_create_link, name='create_news_from_link'),
    url(r'^news/delete/(?P<id>.*)/$', views.news_delete, name='delete_news'),
    url(r'^new/forum/$', views.forum_create, name='forum_create'),
    url(r'^new/comment/forum/$', views.forum_new_comment, name='forum_new_comment'),
    url(r'^remove/forum/$', views.forum_remove, name='forum_remove'),
    url(r'^remove/comment/forum/$', views.forum_remove_comment, name='forum_remove_comment'),
    url(r'^forum/$', views.forum_list, name='forum'),
    url(r'^forum/(?P<title>.*)/$', views.forum, name='forum'),
]
