# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-10 06:36
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(default='CL', max_length=2),
            preserve_default=False,
        ),
    ]
