# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 04:57
from __future__ import unicode_literals

from django.db import migrations, models

def load_stores_from_fixture(apps, schema_editor):
    from django.core.management import call_command
    call_command("loaddata", "login")

class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.RunPython(load_stores_from_fixture),
    ]
