# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
