# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='university',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
