# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-10 06:38
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20161210_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
