# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20160402_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='career',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
