# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-20 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20161019_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_registered',
            field=models.BinaryField(),
        ),
    ]
