# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-07 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20161106_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='drive_email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
