# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_user_career'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mendeley_credentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.BinaryField()),
            ],
        ),
    ]
