# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-20 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20161019_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
    ]
