# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_mendeley_credentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mendeley_credentials',
            name='token',
            field=models.CharField(max_length=500),
        ),
    ]
