# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20160405_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mendeley_credentials',
            name='token',
        ),
        migrations.AddField(
            model_name='mendeley_credentials',
            name='access_token',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mendeley_credentials',
            name='expires_at',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mendeley_credentials',
            name='expires_in',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mendeley_credentials',
            name='msso',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mendeley_credentials',
            name='refresh_token',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mendeley_credentials',
            name='scope',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mendeley_credentials',
            name='token_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
