# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20160405_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='mendeley_credentials',
            name='state',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
