# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_mendeley_credentials_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mendeley_credentials',
            name='refresh_token',
            field=models.BinaryField(),
        ),
    ]
