# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 05:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20160406_0204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mendeley_credentials',
            old_name='refresh_token',
            new_name='token',
        ),
        migrations.RemoveField(
            model_name='mendeley_credentials',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='mendeley_credentials',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='mendeley_credentials',
            name='expires_in',
        ),
        migrations.RemoveField(
            model_name='mendeley_credentials',
            name='msso',
        ),
        migrations.RemoveField(
            model_name='mendeley_credentials',
            name='scope',
        ),
        migrations.RemoveField(
            model_name='mendeley_credentials',
            name='state',
        ),
        migrations.RemoveField(
            model_name='mendeley_credentials',
            name='token_type',
        ),
    ]
