# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_remove_mendeley_credentials_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mendeley_credentials',
            name='expires_at',
        ),
    ]
