# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 23:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_remove_mendeley_credentials_expires_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mendeley_credentials',
        ),
    ]
