# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 06:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_delete_mendeley_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_activity',
            field=models.DateField(auto_now=True, default=datetime.datetime(2016, 4, 10, 6, 29, 28, 283000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.FileField(max_length=500, null=True, upload_to='uploads/profile_pictures/'),
        ),
    ]
