# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_auto_20160410_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='institution',
            field=models.CharField(max_length=50),
        ),
    ]
