# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_auto_20160410_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='doc_count',
            field=models.IntegerField(default=0),
        ),
    ]
