# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-06 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import login.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_user_doc_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='drive_credentials',
            field=login.models.CredentialsField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.FileField(max_length=500, null=True, upload_to='static/profile_pictures/'),
        ),
    ]
