# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-09 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_remove_user_drive_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='drive_credentials',
            field=models.BinaryField(null=True),
        ),
    ]
