# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-07 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0024_auto_20160606_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_module_perms',
            field=models.BooleanField(default=False),
        ),
    ]
