# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-07 01:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0025_user_has_module_perms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_module_perms',
        ),
    ]
