# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-07 01:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0026_remove_user_has_module_perms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_staff',
            new_name='is_admin',
        ),
    ]
