# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-03 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0029_auto_20160702_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
