# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-22 07:02
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.CharField(max_length=700)),
                ('image', models.FileField(max_length=500, null=True, upload_to='static/webpage/images/events/')),
                ('program', models.FileField(max_length=500, null=True, upload_to='static/webpage/files/events/')),
            ],
        ),
        migrations.CreateModel(
            name='EventDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=datetime.date.today)),
                ('begin_hour', models.TimeField(default=django.utils.timezone.now)),
                ('end_hour', models.TimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.Event')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(max_length=500, null=True, upload_to='static/webpage/images/gallery/')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(max_length=500, null=True, upload_to='static/webpage/images/news/')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField()),
                ('working', models.BooleanField(default=True)),
                ('image', models.FileField(max_length=500, null=True, upload_to='static/webpage/images/members/')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('title_html', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(max_length=200, null=True)),
                ('body', models.TextField()),
                ('description', models.TextField(null=True)),
                ('date', models.DateField(default=datetime.date.today, null=True)),
                ('source_text', models.CharField(max_length=200, null=True)),
                ('source_url', models.CharField(max_length=200, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('admin_annotation', models.CharField(max_length=200, null=True)),
                ('thumbnail', models.FileField(max_length=500, null=True, upload_to='static/webpage/images/news/thumbnail/')),
                ('header', models.FileField(max_length=500, null=True, upload_to='static/webpage/images/news/header/')),
                ('in_header', models.BooleanField(default=False)),
                ('is_external', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='News_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now=True)),
                ('seen', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.News')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spanish_name', models.CharField(max_length=50, unique=True)),
                ('english_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('spanish_title', models.CharField(default="<h1 class='c12'></h1>", max_length=200)),
                ('spanish_body', models.TextField(default='<p></p>')),
                ('english_title', models.CharField(default="<h1 class='c12'></h1>", max_length=200)),
                ('english_body', models.TextField(default='<p></p>')),
                ('header', models.FileField(max_length=500, null=True, upload_to='static/webpage/images/sections/header/')),
            ],
        ),
        migrations.CreateModel(
            name='SectionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(max_length=500, null=True, upload_to='static/webpage/images/sections/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.Section')),
            ],
        ),
        migrations.CreateModel(
            name='SubSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spanish_name', models.CharField(max_length=80)),
                ('english_name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('spanish_title', models.CharField(default="<h1 class='c12'></h1>", max_length=200)),
                ('spanish_body', models.TextField(default='<p></p>')),
                ('english_title', models.CharField(default="<h1 class='c12'></h1>", max_length=200)),
                ('english_body', models.TextField(default='<p></p>')),
            ],
        ),
        migrations.CreateModel(
            name='SubSectionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spanish_name', models.CharField(max_length=50)),
                ('english_name', models.CharField(max_length=50)),
                ('image', models.FileField(max_length=500, null=True, upload_to='static/webpage/images/sections/thumbnail/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.Section')),
            ],
        ),
        migrations.AddField(
            model_name='subsection',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.SubSectionCategory'),
        ),
        migrations.AddField(
            model_name='image',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.News'),
        ),
    ]
