# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-13 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(max_length=500, null=True, upload_to='static/webpage/images/gallery/')),
            ],
        ),
    ]
