# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-03 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='english_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='section',
            name='spanish_title',
            field=models.CharField(max_length=200),
        ),
    ]
