# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-18 04:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(max_length=500, null=True, upload_to='static/webpage/images/news/')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(max_length=200, null=True)),
                ('body', models.TextField()),
                ('date', models.DateField(auto_now=True, null=True)),
                ('source_text', models.CharField(max_length=200, null=True)),
                ('source_url', models.CharField(max_length=200, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.News'),
        ),
    ]
