# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-07 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsection',
            name='english_body',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='subsection',
            name='english_title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subsection',
            name='spanish_body',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='subsection',
            name='spanish_title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
