# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-15 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_galleryphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='english_body',
            field=models.TextField(default='<p></p>'),
        ),
        migrations.AlterField(
            model_name='section',
            name='spanish_body',
            field=models.TextField(default='<p></p>'),
        ),
    ]
