# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-10 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_news_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_comment',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
