# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-18 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_auto_20161118_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='title_html',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
