# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-18 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0003_news_title_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='admin_annotation',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
