# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-08 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0003_auto_20161207_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsection',
            name='slug',
            field=models.SlugField(max_length=30, unique=True),
        ),
    ]
