# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-15 04:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0003_auto_20161214_2335'),
        ('webpage', '0003_news_description'),
    ]

    operations = [
    ]
