# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-08 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0004_auto_20161207_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='english_body',
            field=models.TextField(default="<p class='s3 c9'></p>"),
        ),
        migrations.AlterField(
            model_name='section',
            name='english_title',
            field=models.CharField(default="<h1 class='c12'></h1>", max_length=200),
        ),
        migrations.AlterField(
            model_name='section',
            name='spanish_body',
            field=models.TextField(default="<p class='s3 c9'></p>"),
        ),
        migrations.AlterField(
            model_name='section',
            name='spanish_title',
            field=models.CharField(default="<h1 class='c12'></h1>", max_length=200),
        ),
        migrations.AlterField(
            model_name='subsection',
            name='english_body',
            field=models.TextField(default='<p></p>'),
        ),
        migrations.AlterField(
            model_name='subsection',
            name='english_title',
            field=models.CharField(default="<h1 class='c12'></h1>", max_length=200),
        ),
        migrations.AlterField(
            model_name='subsection',
            name='spanish_body',
            field=models.TextField(default='<p></p>'),
        ),
        migrations.AlterField(
            model_name='subsection',
            name='spanish_title',
            field=models.CharField(default="<h1 class='c12'></h1>", max_length=200),
        ),
    ]
