# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-08 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0005_auto_20161208_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsectioncategory',
            name='image',
            field=models.FileField(max_length=500, null=True, upload_to='static/webpage/images/categories/'),
        ),
    ]
