# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-19 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0005_auto_20161119_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='description',
        ),
        migrations.RemoveField(
            model_name='news',
            name='mini_description',
        ),
        migrations.AddField(
            model_name='news',
            name='in_header',
            field=models.BooleanField(default=False),
        ),
    ]
