# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-19 20:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0006_auto_20161119_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
