# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-10 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0006_subsectioncategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsectioncategory',
            name='image',
            field=models.FileField(max_length=500, null=True, upload_to='static/webpage/images/sections/thumbnail/'),
        ),
    ]
