# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-08 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0006_subsectioncategory_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.FileField(max_length=500, null=True, upload_to='static/webpage/images/sections/')),
            ],
        ),
    ]
