# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-19 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0007_auto_20161119_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
    ]
