# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-09 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0008_auto_20161208_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
