# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-02 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0008_news_is_external'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(max_length=500, null=True, upload_to='static/webpage/images/sections/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.Section')),
            ],
        ),
    ]
